import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SearchBar from "./searchbar";
import { useState } from "react";
import { AuthProvider } from "./searchbar";
import NavbarMenu from "./navbar-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
            {children}
          </AuthProvider>
          <NavbarMenu />
          <footer>©️ Copyright Ben Weeks 2024</footer>
      </body>
    </html>
  );
}
